// <auto-generated />
using DataHub.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataHub.Persistence.Migrations
{
    [DbContext(typeof(DataHubContext))]
    [Migration("20221025223004_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataHub.Domain.EnergyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.HasKey("Id")
                        .HasName("PK_energy_report");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("UQ_energy_report_hash");

                    b.ToTable("energy_report", (string)null);
                });

            modelBuilder.Entity("DataHub.Domain.RegionEnergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Energy")
                        .HasColumnType("numeric")
                        .HasColumnName("energy");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.HasKey("Id")
                        .HasName("PK_region_energy");

                    b.HasIndex("Region")
                        .IsUnique()
                        .HasDatabaseName("UQ_region_energy_energy");

                    b.ToTable("region_energy", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
