global using DataHub.Domain;
global using DataHub.Persistence;
global using DataHub.WebApi;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Polly;
global using Serilog;
global using System.Text.Json;